---
abstract: 'AnyEvent HTTP/1.1 Server'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-HTTP-Server
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: '5'
  Digest::SHA1: '2'
  HTTP::Easy: '0.03'
  JSON::XS: '3'
version: '1.99992'
